ProjectReal/urls.py
from django.urls import path
from .views import (home_view,
                    # about_view,
                    # intrests_view,
                    products_view,
                    product_view,
                    # contact_view,
                    )

app_name = 'ProjectReal'

urlpatterns = [
    path('', home_view, name='home-page'),
    path('products/', products_view, name='products-page'),
    path('product/<slug:slug>/', product_view, name='product-page'),
]

THE_YOUNG_BAKER/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('why-are-you-finding-this-page/', admin.site.urls),
    path('project-design/', include('ProjectDesign.urls', namespace='ProjectDesign')),
    path('project-model/', include('ProjectModel.urls', namespace='ProjectModel')),
    path('', include('ProjectReal.urls', namespace='ProjectReal')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

ProjectReal/models.py
from django.db import models

# Create your models here.

ProjectReal/views.py
from django.shortcuts import render, get_object_or_404, get_list_or_404
from ProjectDesign.models import (Home,
                                  Product,
                                  )


def home_view(request):
    home = get_object_or_404(Home, slug='the-young-baker')
    featured_products = get_list_or_404(Product, tag='featured')

    template_name = 'ProjectReal/home-page.html'
    context = {
        'title': 'Home',
        'home': home,
        'featured_products': featured_products
    }
    return render(request, template_name, context)


def products_view(request):
    # categories = get_list_or_404(Category)
    products = Product.objects.all()

    template_name = 'ProjectReal/products-page.html'
    context = {
        'title': 'Products',
        # 'categories': categories,
        'products': products,
    }
    return render(request, template_name, context)


def product_view(request, slug):
    product = get_object_or_404(Product, slug=slug)

    template_name = 'ProjectReal/product-page.html'
    context = {
        'title': product.title,
        'product': product,
    }
    return render(request, template_name, context)

ProjectReal/templates/ProjectReal/extras/base.html
<!DOCTYPE html>
{% load static %}

<html lang="en">
    <head>
        <!-- Required Meta Tags -->
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <!-- Box Icons -->
        <link href='https://cdn.jsdelivr.net/npm/boxicons@2.0.5/css/boxicons.min.css' rel='stylesheet'>

        <!-- CSS -->
        <link rel="stylesheet" href="{% static 'ProjectReal/css/style.css' %}">

        <!-- Title -->
        {% if title %}
            <title>The Young Baker - {{ title }}</title>
        {% else %}
            <title>The Young Baker</title>
        {% endif %}

    </head>
    <body>

        <!-- Header -->
        {% include 'ProjectReal/extras/header.html' %}

        <!-- Content -->
        {% block content %}
        {% endblock content %}

        <!-- Footer -->
        {% include 'ProjectReal/extras/footer.html' %}

        <!-- Scroll Top -->
        <a href="#" class="scrolltop" id="scroll-top">
            <i class='bx bx-chevron-up scrolltop__icon'></i>
        </a>

        <!-- Scroll Reveal -->
        <script src="https://unpkg.com/scrollreveal"></script>

        <!-- Javascript -->
        <script src="{% static 'ProjectReal/js/script.js' %}"></script>
    </body>
</html>

ProjectReal/templates/ProjectReal/extras/footer.html
<!-- Footer -->
<footer class="footer section bd-container">
    <div class="footer__container bd-grid">
        <div class="footer__content">
            <a href="#" class="footer__logo">The Young Baker </a>
            <span class="footer__description">Cake Bakery</span>
            <div>
                <a href="#" class="footer__social"><i class='bx bxl-facebook'></i></a>
                <a href="#" class="footer__social"><i class='bx bxl-instagram'></i></a>
                <a href="#" class="footer__social"><i class='bx bxl-twitter'></i></a>
            </div>
        </div>

        <div class="footer__content">
            <h3 class="footer__title">Services</h3>
            <ul>
                <li><a href="#" class="footer__link">Delivery</a></li>
                <li><a href="#" class="footer__link">Pricing</a></li>
                <li><a href="#" class="footer__link">Fast food</a></li>
                <li><a href="#" class="footer__link">Reserve your spot</a></li>
            </ul>
        </div>

        <div class="footer__content">
            <h3 class="footer__title">Information</h3>
            <ul>
                <li><a href="#" class="footer__link">Event</a></li>
                <li><a href="#" class="footer__link">Contact us</a></li>
                <li><a href="#" class="footer__link">Privacy policy</a></li>
                <li><a href="#" class="footer__link">Terms of services</a></li>
            </ul>
        </div>

        <div class="footer__content">
            <h3 class="footer__title">Adress</h3>
            <ul>
                <li>Nagpur, Maharashtra</li>
                <li>India 440009</li>
                <li>999 - 888 - 777</li>
                <li>theyoungbaker@gmail.com</li>
            </ul>
        </div>
    </div>

    <p class="footer__copy">&#169; 2020 Bedimcode. All right reserved</p>
</footer>

ProjectReal/templates/ProjectReal/extras/header.html
<!-- Header -->
{% load static %}

<header class="l-header" id="header">
    <nav class="nav bd-container">
        <a href="{% url 'ProjectReal:home-page' %}" class="nav__logo">The Young Baker</a>

        <div class="nav__menu" id="nav-menu">
            <ul class="nav__list">
                <li class="nav__item"><a href="{% url 'ProjectReal:home-page' %}" class="nav__link active-link">Home</a></li>
                <li class="nav__item"><a href="#services" class="nav__link">Services</a></li>
                <li class="nav__item"><a href="{% url 'ProjectReal:products-page' %}" class="nav__link">Menu</a></li>
                <li class="nav__item"><a href="#about" class="nav__link">About</a></li>
                <li class="nav__item"><a href="#contact" class="nav__link">Contact</a></li>

                <li><i class='bx bx-moon change-theme' id="theme-button"></i></li>
            </ul>
        </div>

        <div class="nav__toggle" id="nav-toggle">
            <i class='bx bx-menu'></i>
        </div>
    </nav>
</header>