ProjectModel/urls.py
from django.urls import path
from .views import (home_view,
                    category_view,
                    products_view,
                    product_view,
                    about_view,
                    contact_view)

app_name = 'ProjectModel'

urlpatterns = [
    path('', home_view, name='home-page'),
    path('category/<slug:slug>/', category_view, name='category-page'),
    path('products/', products_view, name='products-page'),
    path('product/<slug:slug>', product_view, name='product-page'),
    path('about/', about_view, name='about-page'),
    path('contact/', contact_view, name='contact-page'),
]

ProjectReal/urls.py
from django.urls import path
from .views import (home_view,
                    # about_view,
                    # intrests_view,
                    products_view,
                    product_view,
                    # contact_view,
                    )

app_name = 'ProjectReal'

urlpatterns = [
    path('', home_view, name='home-page'),
    path('products/', products_view, name='products-page'),
    path('product/<slug:slug>/', product_view, name='product-page'),
]

THE_YOUNG_BAKER/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('why-are-you-finding-this-page/', admin.site.urls),
    path('project-design/', include('ProjectDesign.urls', namespace='ProjectDesign')),
    path('project-model/', include('ProjectModel.urls', namespace='ProjectModel')),
    path('', include('ProjectReal.urls', namespace='ProjectReal')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

ProjectModel/models.py
from django.db import models

# Create your models here.

ProjectModel/views.py
from django.shortcuts import render, get_object_or_404, get_list_or_404
from django.contrib.admin.views.decorators import staff_member_required
from ProjectDesign.models import (Home,
                                  Category,
                                  Product,
                                  )


def home_view(request):
    home = get_object_or_404(Home, title='The Young Baker')
    categories = get_list_or_404(Category)
    featured_products = get_list_or_404(Product, tag='featured')

    template_name = 'ProjectModel/home-page.html'
    context = {
        'title': 'Home',
        'home': home,
        'categories': categories,
        'featured_products': featured_products,
    }
    return render(request, template_name, context)


def category_view(request, slug):
    categories = get_list_or_404(Category)
    category = get_object_or_404(Category, slug=slug)

    template_name = 'ProjectModel/category-page.html'
    context = {
        'title': category.title,
        'categories': categories,
        'category': category,
    }
    return render(request, template_name, context)


def products_view(request):
    categories = get_list_or_404(Category)
    products = Product.objects.all()

    template_name = 'ProjectModel/b-products-page.html'
    context = {
        'title': 'Products',
        'categories': categories,
        'products': products,
    }
    return render(request, template_name, context)


def product_view(request, slug):
    product = get_object_or_404(Product, slug=slug)

    template_name = 'ProjectModel/c-product-page.html'
    context = {
        'title': product.title,
        'product': product,
    }
    return render(request, template_name, context)


def about_view(request):
    template_name = 'ProjectModel/d-about-page.html'
    context = {
        'title': 'About',
    }
    return render(request, template_name, context)


def contact_view(request):
    template_name = 'ProjectModel/e-contact-page.html'
    context = {
        'title': 'Contact',
    }
    return render(request, template_name, context)

ProjectModel/templates/ProjectModel/extras/base.html
<!doctype html>
{% load static %}

<html lang="en">
<head>
    <!-- Required Meta Tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Tailwind CSS -->
    <link href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css" rel="stylesheet">

    <!-- Title -->
    {% if title %}
        <title>The Young Baker - Project Model - {{ title }}</title>
    {% else %}
        <title>The Young Baker - Project Model</title>
    {% endif %}

</head>
<body>
    <!-- Header -->
    {% include 'ProjectModel/extras/header.html' %}

    <!-- Content -->
    {% block content %}
    {% endblock content %}

    <!-- Footer -->
    {% include 'ProjectModel/extras/footer.html' %}

</body>
</html>

ProjectModel/templates/ProjectModel/extras/footer.html
{% load static %}

<footer class="text-gray-400 bg-gray-900 body-font">
  <div class="container px-5 py-24 mx-auto flex md:items-center lg:items-start md:flex-row md:flex-nowrap flex-wrap flex-col">
    <div class="w-64 flex-shrink-0 md:mx-0 mx-auto text-center md:text-left">
        <a class="flex title-font font-medium items-center md:justify-start justify-center text-white">
            <img class="h-16" src="{% static 'ProjectModel/images/shree-krupa.png' %}" alt="">
            <span class="ml-3 text-xl">Shreekrupa Agarbatti</span>
        </a>
      <p class="mt-2 text-sm text-gray-500">Air plant banjo lyft occupy retro adaptogen indego</p>
    </div>
    <div class="flex-grow flex flex-wrap md:pl-20 -mb-10 md:mt-0 mt-10 md:text-left text-center">
      <div class="lg:w-1/4 md:w-1/2 w-full px-4">
        <h2 class="title-font font-medium text-white tracking-widest text-sm mb-3">CATEGORIES</h2>
        <nav class="list-none mb-10">
          <li>
            <a class="text-gray-400 hover:text-white">First Link</a>
          </li>
          <li>
            <a class="text-gray-400 hover:text-white">Second Link</a>
          </li>
          <li>
            <a class="text-gray-400 hover:text-white">Third Link</a>
          </li>
          <li>
            <a class="text-gray-400 hover:text-white">Fourth Link</a>
          </li>
        </nav>
      </div>
      <div class="lg:w-1/4 md:w-1/2 w-full px-4">
        <h2 class="title-font font-medium text-white tracking-widest text-sm mb-3">CATEGORIES</h2>
        <nav class="list-none mb-10">
          <li>
            <a class="text-gray-400 hover:text-white">First Link</a>
          </li>
          <li>
            <a class="text-gray-400 hover:text-white">Second Link</a>
          </li>
          <li>
            <a class="text-gray-400 hover:text-white">Third Link</a>
          </li>
          <li>
            <a class="text-gray-400 hover:text-white">Fourth Link</a>
          </li>
        </nav>
      </div>
      <div class="lg:w-1/4 md:w-1/2 w-full px-4">
        <h2 class="title-font font-medium text-white tracking-widest text-sm mb-3">CATEGORIES</h2>
        <nav class="list-none mb-10">
          <li>
            <a class="text-gray-400 hover:text-white">First Link</a>
          </li>
          <li>
            <a class="text-gray-400 hover:text-white">Second Link</a>
          </li>
          <li>
            <a class="text-gray-400 hover:text-white">Third Link</a>
          </li>
          <li>
            <a class="text-gray-400 hover:text-white">Fourth Link</a>
          </li>
        </nav>
      </div>
      <div class="lg:w-1/4 md:w-1/2 w-full px-4">
        <h2 class="title-font font-medium text-white tracking-widest text-sm mb-3">CATEGORIES</h2>
        <nav class="list-none mb-10">
          <li>
            <a class="text-gray-400 hover:text-white">First Link</a>
          </li>
          <li>
            <a class="text-gray-400 hover:text-white">Second Link</a>
          </li>
          <li>
            <a class="text-gray-400 hover:text-white">Third Link</a>
          </li>
          <li>
            <a class="text-gray-400 hover:text-white">Fourth Link</a>
          </li>
        </nav>
      </div>
    </div>
  </div>
  <div class="bg-gray-800 bg-opacity-75">
    <div class="container mx-auto py-4 px-5 flex flex-wrap flex-col sm:flex-row">
      <p class="text-gray-400 text-sm text-center sm:text-left">© 2020 Tailblocks —
        <a href="https://twitter.com/knyttneve" rel="noopener noreferrer" class="text-gray-500 ml-1" target="_blank">@knyttneve</a>
      </p>
      <span class="inline-flex sm:ml-auto sm:mt-0 mt-2 justify-center sm:justify-start">
        <a class="text-gray-400">
          <svg fill="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-5 h-5" viewBox="0 0 24 24">
            <path d="M18 2h-3a5 5 0 00-5 5v3H7v4h3v8h4v-8h3l1-4h-4V7a1 1 0 011-1h3z"></path>
          </svg>
        </a>
        <a class="ml-3 text-gray-400">
          <svg fill="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-5 h-5" viewBox="0 0 24 24">
            <path d="M23 3a10.9 10.9 0 01-3.14 1.53 4.48 4.48 0 00-7.86 3v1A10.66 10.66 0 013 4s-4 9 5 13a11.64 11.64 0 01-7 2c9 5 20 0 20-11.5a4.5 4.5 0 00-.08-.83A7.72 7.72 0 0023 3z"></path>
          </svg>
        </a>
        <a class="ml-3 text-gray-400">
          <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-5 h-5" viewBox="0 0 24 24">
            <rect width="20" height="20" x="2" y="2" rx="5" ry="5"></rect>
            <path d="M16 11.37A4 4 0 1112.63 8 4 4 0 0116 11.37zm1.5-4.87h.01"></path>
          </svg>
        </a>
        <a class="ml-3 text-gray-400">
          <svg fill="currentColor" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="0" class="w-5 h-5" viewBox="0 0 24 24">
            <path stroke="none" d="M16 8a6 6 0 016 6v7h-4v-7a2 2 0 00-2-2 2 2 0 00-2 2v7h-4v-7a6 6 0 016-6zM2 9h4v12H2z"></path>
            <circle cx="4" cy="4" r="2" stroke="none"></circle>
          </svg>
        </a>
      </span>
    </div>
  </div>
</footer>

ProjectModel/templates/ProjectModel/extras/header.html
{% load static %}

<header class="text-gray-400 bg-gray-900 body-font">
  <div class="container mx-auto flex flex-wrap p-5 flex-col md:flex-row items-center">
    <a class="flex title-font font-medium items-center text-white mb-4 md:mb-0">
        <img class=" h-16"
             src="{% static 'ProjectModel/images/shree-krupa.png' %}" alt="">
        <span class="ml-3 text-xl">The Young Baker</span>
    </a>
    <nav class="md:ml-auto flex flex-wrap items-center text-base justify-center">
        <b><a href="{% url 'ProjectModel:home-page' %}" class="mr-5 hover:text-white">Home</a></b>
        <b><a href="{% url 'ProjectModel:products-page' %}" class="mr-5 hover:text-white">Products</a></b>
        <b><a href="{% url 'ProjectModel:about-page' %}" class="mr-5 hover:text-white">About</a></b>
        <b><a href="{% url 'ProjectModel:contact-page' %}" class="mr-5 hover:text-white">Contact</a></b>
    </nav>

  </div>
</header>